# Generated by Django 4.2.2 on 2023-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="neeeds a bio", max_length=500),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                default="\\media\\defult.jpg", upload_to="profile_pics"
            ),
        ),
    ]
