# Generated by Django 4.2.2 on 2023-07-03 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
