# Generated by Django 4.2.2 on 2023-07-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(default="address", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="city", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="first name", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="last name", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(default="phone", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(default="state", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="zipcode",
            field=models.CharField(default="zipcode", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(default="defult.jpg", upload_to="profile_pics"),
        ),
    ]
