# Generated by Django 4.2.2 on 2023-07-03 19:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_userprofile_address_userprofile_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustom",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.CharField(default="address", max_length=50)),
                ("city", models.CharField(default="city", max_length=50)),
                ("state", models.CharField(default="state", max_length=50)),
                ("zipcode", models.CharField(default="zipcode", max_length=50)),
                ("phone", models.CharField(default="phone", max_length=50)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
